services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: splash-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend-data:/app/data
    environment:
      - DATABASE_URL=postgresql+asyncpg://splash:splash@postgres:5432/splash
      - PYTHONPATH=/app
      - RELOAD_FLAG=--reload
      - LOG_LEVEL=debug
    networks:
      - splash-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    # env_file:
    #   - ./backend/.env.local

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: splash-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_LITELLM_URL=http://localhost:4000
      - NODE_ENV=development
    depends_on:
      - backend
      - litellm
    networks:
      - splash-network
    env_file:
      - ./frontend/.env.local

  litellm:
    image: ghcr.io/berriai/litellm:main-stable
    container_name: splash-litellm
    ports:
      - "4000:4000"
    volumes:
      - ./litellm_config.yaml:/app/config.yaml
    environment:
      - LITELLM_MASTER_KEY=sk-splash-master-key-1234
      - GEMINI_API_KEY=AIzaSyD1WlO2hJMzDZx2jqlNOzee4J7yuccvYUs
      - LITELLM_MODE=DEVELOPMENT
      - UI_USERNAME=admin
      - UI_PASSWORD=admin
      - DATABASE_URL=postgresql://litellm:litellm@postgres:5432/litellm
      - LITELLM_SALT_KEY=sk-12345678
      - STORE_MODEL_IN_DB=True
    command: --config /app/config.yaml --port 4000
    depends_on:
      - postgres
    networks:
      - splash-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:15-alpine  # Using specific version for better caching
    container_name: splash-postgres
    environment:
      - POSTGRES_USER=splash
      - POSTGRES_PASSWORD=splash
      - POSTGRES_DB=splash
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - splash-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U splash"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  backend-data:
  postgres_data:

networks:
  splash-network:
    driver: bridge