create table "public"."users" (
    "id" int4 generated by default as identity not null PRIMARY KEY,
    "supabase_id" character varying NOT NULL UNIQUE,
    "email" character varying NOT NULL UNIQUE,
    "name" character varying,
    "role" character varying NOT NULL,
    "created_at" timestamp(6) without time zone NOT NULL,
    "last_seen" timestamp(6) without time zone NOT NULL
);

create table "public"."resumes" (
    "id" int4 generated by default as identity not null PRIMARY KEY,
    "user_id" int4 REFERENCES users(id),
    "name" character varying NOT NULL,
    "email" character varying NOT NULL,
    "phone" character varying,
    "title" character varying,
    "experience_years" integer,
    "education" character varying,
    "summary" character varying,
    "created_at" timestamp(6) without time zone NOT NULL,
    "skills" json
);

create table "public"."waitlist" (
    "email" character varying PRIMARY KEY,
    "info" json,
    "created_at" timestamp(6) without time zone,
    "updated_at" timestamp(6) without time zone
);

-- Additional indexes for performance
CREATE INDEX ix_resumes_email ON public.resumes (email);
CREATE INDEX ix_resumes_user_id ON public.resumes (user_id);
CREATE INDEX ix_waitlist_created_at ON public.waitlist (created_at);
